// Данные автомобилей автосалона AutoPremium
const carsData = [
  // Премиум-сегмент (4 шт)
  {
    id: 1,
    name: "BMW 5 Series 520i",
    brand: "BMW",
    price: 4500000,
    originalPrice: 4800000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1749566710691-f959646d0330?w=800",
    category: "Премиум",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 2,
    name: "Audi A6 55 TFSI quattro",
    brand: "Audi",
    price: 4200000,
    originalPrice: 4500000,
    year: 2024,
    mileage: 0,
    engine: "3.0L V6 Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Премиум",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 3,
    name: "Mercedes-Benz E-Class E300",
    brand: "Mercedes-Benz",
    price: 4700000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Премиум",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 4,
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    price: 8500000,
    originalPrice: 9200000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1572029117144-b991c2eaee93?w=800",
    category: "Премиум",
    available: false,
    features: ["Автопилот", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Спорткары (4 шт)
  {
    id: 5,
    name: "Porsche 911 Carrera",
    brand: "Porsche",
    price: 9500000,
    originalPrice: 10200000,
    year: 2024,
    mileage: 0,
    engine: "3.0L Twin-Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1629554572869-1b9decad7198?w=800",
    category: "Спорткары",
    available: true,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Спортивные сиденья", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 6,
    name: "BMW M3 Competition",
    brand: "BMW",
    price: 6800000,
    year: 2024,
    mileage: 0,
    engine: "3.0L Twin-Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1749566710691-f959646d0330?w=800",
    category: "Спорткары",
    available: true,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Спортивные сиденья", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 7,
    name: "Audi RS5 Sportback",
    brand: "Audi",
    price: 7200000,
    originalPrice: 7800000,
    year: 2024,
    mileage: 0,
    engine: "2.9L Twin-Turbo V6",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Спорткары",
    available: true,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Спортивные сиденья", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 8,
    name: "Chevrolet Camaro ZL1",
    brand: "Chevrolet",
    price: 5500000,
    year: 2024,
    mileage: 0,
    engine: "6.2L V8 Supercharged",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1546716148-b4d27fc8930c?w=800",
    category: "Спорткары",
    available: true,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Спортивные сиденья", "Bluetooth", "USB/AUX", "ABS"]
  },

  // SUV (4 шт)
  {
    id: 9,
    name: "Toyota RAV4 Hybrid",
    brand: "Toyota",
    price: 2800000,
    year: 2024,
    mileage: 0,
    engine: "2.5L Hybrid",
    transmission: "CVT",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1683965362932-9d4224e6904f?w=800",
    category: "SUV",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 10,
    name: "Honda CR-V Hybrid",
    brand: "Honda",
    price: 2650000,
    originalPrice: 2850000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Hybrid",
    transmission: "CVT",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1720236177685-b62ffa6377aa?w=800",
    category: "SUV",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 11,
    name: "Range Rover Evoque",
    brand: "Land Rover",
    price: 4200000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1506616995931-556bc0c90c16?w=800",
    category: "SUV",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 12,
    name: "BMW X5 xDrive40i",
    brand: "BMW",
    price: 5800000,
    year: 2024,
    mileage: 0,
    engine: "3.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1749566710691-f959646d0330?w=800",
    category: "SUV",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Седаны (4 шт)
  {
    id: 13,
    name: "Toyota Camry 2.5 Hybrid",
    brand: "Toyota",
    price: 2400000,
    originalPrice: 2600000,
    year: 2024,
    mileage: 0,
    engine: "2.5L Hybrid",
    transmission: "CVT",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1683965362932-9d4224e6904f?w=800",
    category: "Седаны",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 14,
    name: "Honda Accord Hybrid",
    brand: "Honda",
    price: 2200000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Hybrid",
    transmission: "CVT",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1720236177685-b62ffa6377aa?w=800",
    category: "Седаны",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 15,
    name: "Volkswagen Passat 2.0 TSI",
    brand: "Volkswagen",
    price: 2500000,
    originalPrice: 2700000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Седаны",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 16,
    name: "Hyundai Sonata Hybrid",
    brand: "Hyundai",
    price: 2100000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Hybrid",
    transmission: "Автомат",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Седаны",
    available: false,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Пикапы (4 шт)
  {
    id: 17,
    name: "Ford F-150 Lightning Electric",
    brand: "Ford",
    price: 6200000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1590053936004-faca6038bfec?w=800",
    category: "Пикапы",
    available: true,
    features: ["Полный привод", "Электрическая платформа", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 18,
    name: "Toyota Hilux 2.8D",
    brand: "Toyota",
    price: 3200000,
    originalPrice: 3500000,
    year: 2024,
    mileage: 0,
    engine: "2.8L Diesel",
    transmission: "Автомат",
    fuelType: "Дизель",
    image: "https://images.unsplash.com/photo-1683965362932-9d4224e6904f?w=800",
    category: "Пикапы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 19,
    name: "Chevrolet Silverado 1500",
    brand: "Chevrolet",
    price: 4800000,
    originalPrice: 5200000,
    year: 2024,
    mileage: 0,
    engine: "5.3L V8",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1546716148-b4d27fc8930c?w=800",
    category: "Пикапы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 20,
    name: "Isuzu D-Max 3.0 4WD",
    brand: "Isuzu",
    price: 2800000,
    year: 2024,
    mileage: 0,
    engine: "3.0L Diesel",
    transmission: "Автомат",
    fuelType: "Дизель",
    image: "https://images.unsplash.com/photo-1590053936004-faca6038bfec?w=800",
    category: "Пикапы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Хэтчбеки (4 шт)
  {
    id: 21,
    name: "Volkswagen Golf GTI",
    brand: "Volkswagen",
    price: 2200000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Хэтчбеки",
    available: false,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 22,
    name: "Honda Civic Type R",
    brand: "Honda",
    price: 3500000,
    originalPrice: 3800000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Turbo",
    transmission: "Механика",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1720236177685-b62ffa6377aa?w=800",
    category: "Хэтчбеки",
    available: true,
    features: ["Спортивная подвеска", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Спортивные сиденья", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 23,
    name: "Audi A3 Sportback",
    brand: "Audi",
    price: 2600000,
    year: 2024,
    mileage: 0,
    engine: "1.5L TFSI",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Хэтчбеки",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 24,
    name: "BMW 1 Series 118i",
    brand: "BMW",
    price: 2300000,
    originalPrice: 2500000,
    year: 2024,
    mileage: 0,
    engine: "1.5L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1749566710691-f959646d0330?w=800",
    category: "Хэтчбеки",
    available: true,
    features: ["Кондиционер", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Электромобили (4 шт)
  {
    id: 25,
    name: "Tesla Model 3 Long Range",
    brand: "Tesla",
    price: 4500000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1572029117144-b991c2eaee93?w=800",
    category: "Электромобили",
    available: true,
    features: ["Автопилот", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 26,
    name: "BMW iX xDrive50",
    brand: "BMW",
    price: 7200000,
    originalPrice: 7800000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1749566710691-f959646d0330?w=800",
    category: "Электромобили",
    available: true,
    features: ["Автопилот", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 27,
    name: "Audi e-tron GT",
    brand: "Audi",
    price: 8800000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Электромобили",
    available: true,
    features: ["Автопилот", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 28,
    name: "Mercedes EQS 450+",
    brand: "Mercedes-Benz",
    price: 9500000,
    originalPrice: 10200000,
    year: 2024,
    mileage: 0,
    engine: "Электро",
    transmission: "Автомат",
    fuelType: "Электро",
    image: "https://images.unsplash.com/photo-1728236436940-10b097998033?w=800",
    category: "Электромобили",
    available: false,
    features: ["Автопилот", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },

  // Кроссоверы (4 шт)
  {
    id: 29,
    name: "Mazda CX-5 2.5 Turbo",
    brand: "Mazda",
    price: 2500000,
    year: 2024,
    mileage: 0,
    engine: "2.5L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Кроссоверы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 30,
    name: "Nissan Qashqai 1.3 DIG-T",
    brand: "Nissan",
    price: 2300000,
    originalPrice: 2500000,
    year: 2024,
    mileage: 0,
    engine: "1.3L Turbo",
    transmission: "Автомат",
    fuelType: "Бензин",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Кроссоверы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 31,
    name: "Hyundai Tucson Hybrid",
    brand: "Hyundai",
    price: 2400000,
    year: 2024,
    mileage: 0,
    engine: "1.6L Hybrid",
    transmission: "Автомат",
    fuelType: "Гибрид",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Кроссоверы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  },
  {
    id: 32,
    name: "Kia Sportage 2.0 CRDI",
    brand: "Kia",
    price: 2200000,
    originalPrice: 2400000,
    year: 2024,
    mileage: 0,
    engine: "2.0L Diesel",
    transmission: "Автомат",
    fuelType: "Дизель",
    image: "https://images.unsplash.com/photo-1708957398024-9100292f51be?w=800",
    category: "Кроссоверы",
    available: true,
    features: ["Полный привод", "Круиз-контроль", "Парктроник", "Камера заднего вида", "Подогрев сидений", "Bluetooth", "USB/AUX", "ABS"]
  }
];
